apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-mysql
  namespace: final
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  selector:
    matchLabels:
      name: simple-webapp-mysql
      component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-mysql
        component: frontend
    spec:
      serviceAccountName: clo835
      containers:
      - name: clo835finalproject
        image: 083477265364.dkr.ecr.us-east-1.amazonaws.com/clo835finalproject:webappmysql
        resources:
          requests:
            cpu: 200m
        ports:
        - containerPort: 81
        envFrom:
          - secretRef:
              name: project-secret
          - configMapRef:
              name: project-config


