apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-webapp-mysql
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-webapp-mysql
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: clo835
      containers:
      - name: clo835finalproject
        image: 083477265364.dkr.ecr.us-east-1.amazonaws.com/clo835finalproject:webappmysql
        ports:
        - containerPort: 81
        envFrom:
          - secretRef:
              name: project-secret
          - configMapRef:
              name: project-config


