apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: final
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-pvc
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: paswrd
    envFrom:
      - secretRef:
          name: project-secret
  volumes:
    - name: mysql-pvc
      persistentVolumeClaim:
        claimName: mysql-pvc
