apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::881740801742:role/eksctl-clo835-addon-iamserviceaccount-final-Role1-M7DN6QJBS8H6"